### ISSUE TITLE
Failed to resolve:  com.github.vajro:MaterialDesignLibrary:1.6

### ISSUE THREAD

**Issue by crgarridos** [edsilfer/android-list-manager#1]
Hello, the lib looks great. I just wanted to gave it a try but i getting the follow error after adding it to my build.gradle

![capture](https://cloud.githubusercontent.com/assets/2308331/20351730/9524753c-ac14-11e6-80ad-50b2b6d2dced.PNG)
 
I leave here some information from my build.gradle. I'm using kotlin plugin version 1.0.5
```
    compileSdkVersion 25
    buildToolsVersion "24.0.2"
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
    }
```

Thanks

**Comment by edsilfer** [comment]
Hi! My fault! This is happening because one of its dependencies is not yet on JCenter. I'll fix that on the next release, meanwhile you can add the following repository to your gradle file:

```groovy
repositories {
    maven { url "https://jitpack.io" }
}
```

**Comment by crgarridos** [comment]
Thanks, that works fine !

But now I'm getting an error with the minVersion (21). I'm using the 16. you should down it or specify in the README that is not compatible with API < 21. 

![capture](https://cloud.githubusercontent.com/assets/2308331/20352485/b53d0976-ac17-11e6-828b-f01e6d05822c.PNG)

I can't see why you are limiting the version, I guess it is just based in the design library.

**Comment by edsilfer** [comment]
Actually I have another library which is API min 18. I'll see if I can decrease it as well and release another version

**Comment by edsilfer** [comment]
Min API version was reduced to 16, READE-ME updated.
